Increment version number and CHANGELOG to close Milestone 2
TrustTheVote-Project/BallotLab pull request #118
Opened 2022-09-20 16:33 UTC by stratofax

Not much going on here but this is what it looks like when I increment the version number.

2022-09-20 18:29 UTC, ion-oset requested changes

2022-09-20 18:29 UTC, ion-oset commented on CHANGELOG.md
> +## 0.1.3 -- September 20, 2022
```suggestion
## 0.1.3 - September 20, 2022
```

2022-09-20 18:29 UTC, ion-oset commented on CHANGELOG.md
> +Complete [2. Generate ballot PDFs with embedded form objects Milestone](https://github.com/TrustTheVote-Project/BallotLab/milestone/2)
```suggestion
Completed [Milestone 2. Generate ballot PDFs with embedded form objects Milestone](https://github.com/TrustTheVote-Project/BallotLab/milestone/2)
```

2022-09-20 18:29 UTC, ion-oset commented on CHANGELOG.md
>  Complete Milestone 1: flat file PDF. Notable features include:
```suggestion
Completed milestone 1: [Generate flat PDFs from Jetsons EDF](https://github.com/TrustTheVote-Project/BallotLab/milestone/1)
```

2022-09-21 17:08 UTC, stratofax commented
@ion-oset I believe I made all the changes you requested, and also removed a considerable amount of dead or unneeded code. Please take a last look and then I'll merge this work onto `development` and then onto main.

Thanks again for your excellent reviews!

2022-09-21 21:21 UTC, ion-oset approved these changes
LGTM :+1:

I think this PR warrants a squash merge.

2022-09-22 14:37 UTC, stratofax commented
Agreed: squash merge.

2022-09-22 14:38 UTC, merged